export { default as Home } from './users/HomePage';
export { default as Bookings } from './users/Bookings';
export { default as BookingCard } from './users/BookingCard';
export { default as LandingPage } from './users/LandingPage';
export { default as AdminHome } from './admin/AdminHome';
export { default as AdminBookings } from './admin/AdminBookings';
export { default as AdminSlotDesign } from './admin/AdminSlotDesign';
export { default as AdminUsers } from './admin/AdminUsers';
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'